name: new_york_time_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  url_launcher: ^6.2.2
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true




# import 'package:url_launcher/url_launcher.dart';

# openBrowser({required String urlArt}) async {
#   final Uri url = Uri.parse(urlArt);
#   await launchUrl(url);
# }